### ISSUE TITLE
Preserve old links

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/thanks#1]
Commit 10b75f7f310fe3c554ab3419648579ee75384adc is going to break all links pointing to thanks. We should either revert the commit or implement redirects if we prefer the new paths.

**Comment by Mark-Simulacrum** [comment]
Yes, I did this initially because I was having trouble with getting the paths to work given the new hosting; specifically `/rust/1.34.0` would redirect to the gh-pages site instead of staying on thanks-new.rust-lang.org which, of course, didn't work. I didn't try to investigate too much though.
