### ISSUE TITLE
Duplicates in list

### ISSUE THREAD

**Issue by phansch** [rust-lang/thanks#14]
It looks like at least the 1.35 list of contributors contains some duplicates:

https://thanks.rust-lang.org/rust/1.35.0/

Some examples include:

* Alex Gaynor
* André Vicente Milack
* Jethro Beekman
* Kornel Lesiński

**Comment by varkor** [comment]
The reason for this is that these authors have committed using different email addresses. E.g. Jethro Beekman is associated both with `jethro@jbeekman.nl` and `jethro@fortanix.com`. These should be fixed in the [mailmap](https://github.com/rust-lang/rust/blob/master/.mailmap).

**Comment by phansch** [comment]
Alright, going to close this issue then. I suppose one could add a check to `tidy` to ensure that the mailmap is correctly formatted?
