### ISSUE TITLE
Extract mailmap handling into separate crate

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/thanks#2]
We would at least like to use it to validate the mailmap in rust-lang/rust; it seems potentially more broadly useful as well.

**Comment by XAMPPRocky** [comment]
Looking at the repo it seems you have done this since opening this issue, so should we close or is there more to the feature?

**Comment by Mark-Simulacrum** [comment]
Ah, I would still like to eventually add the validation to tidy, but that doesn't need to be tracked here.
