### ISSUE TITLE
Add a static JSON API?

### ISSUE THREAD

**Issue by camelid** [rust-lang/thanks#26]
Add a static JSON API. Basically a machine-readable version of each page (all time, master, 1.46.0, 1.45.2, etc.).

**Comment by camelid** [comment]
I would be interested in trying to implement this if it's accepted.

**Comment by Mark-Simulacrum** [comment]
What would the intended use case be? In some sense I would prefer to avoid lending more than a passing amount of interest into the data gathered here as it's definitely not even ~50% representative of all Rust contributions probably and I worry that an API makes folks more likely to read more into the data than they should.

**Comment by camelid** [comment]
Good point :)

I wanted to make a graph because I was curious about how steep the dropoff was for commit count. Some people have many thousands of commits, but it drops off really fast to hundreds, and I was curious to see what it looked like. I ended up scraping the page and it wasn't too hard.

I'll close this because if people really want to access the data they can scrape it.

**Comment by pietroalbini** [comment]
Just as a note, running the tool on my machine takes less than a minute, so it's not impossibly slow to scrape.
