### ISSUE TITLE
Duplicate entry

### ISSUE THREAD

**Issue by lnicola** [rust-lang/thanks#27]
I just noticed I'm listed twice on https://thanks.rust-lang.org/rust/all-time/ (Laurențiu Nicola). I _think_ my mailmap entry is fine, though, and `git log --author Laurențiu` doesn't list anyone else.

**Comment by Mark-Simulacrum** [comment]
https://github.com/rust-lang/rust/commit/5cc93950acb18c5b0978583ea518940336e847af is co-authored by you, with the email being lnicola@users.noreply.github.com. I would be happy to take a PR to the rust-lang/rust mailmap file, but this doesn't appear to be a bug, so going to close this issue.

**Comment by lnicola** [comment]
Ah, sorry. Thank you.
