### ISSUE TITLE
Reviewers of rolled-up PRs are not counted

### ISSUE THREAD

**Issue by m-ou-se** [rust-lang/thanks#30]
The 'Create a rollup' button above bors' queue creates the merge commits (with `r=reviewer`) with the author set to the creator of the rollup, and the committer set to `GitHub <noreply@github.com>`. But `thanks` only looks for reviewers in merge commits where both the author and committer is `bors`.

**Comment by Mark-Simulacrum** [comment]
Huh, this might be a recent regression; I thought I specifically aimed to handle this. I'd be happy to accept a PR.

**Comment by Mark-Simulacrum** [comment]
I imagine we can look for "rollup merge of" in the commit message.
