### ISSUE TITLE
Cannot compile "thanks" when compiling crate "libz-sys v1.0.25"

### ISSUE THREAD

**Issue by tomaswuhua123** [rust-lang/thanks#33]
Here is error in detail:
//
The following warnings were emitted during compilation:

warning: cc1.exe: sorry, unimplemented: 64-bit mode not compiled in

error: failed to run custom build command for `libz-sys v1.0.25`

Caused by:
  process didn't exit successfully: `G:\Programs\thanks\target\release\build\libz-sys-5a36940f5572e7bd\build-script-build` (exit code: 1)
  --- stdout
  cargo:rerun-if-env-changed=LIBZ_SYS_STATIC
  cargo:rerun-if-changed=build.rs
  TARGET = Some("x86_64-pc-windows-gnu")
  OPT_LEVEL = Some("3")
  HOST = Some("x86_64-pc-windows-gnu")
  CC_x86_64-pc-windows-gnu = None
  CC_x86_64_pc_windows_gnu = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-pc-windows-gnu = None
  CFLAGS_x86_64_pc_windows_gnu = None
  HOST_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("true")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  running: "gcc.exe" "-O3" "-ffunction-sections" "-fdata-sections" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "src/zlib" "-o" "G:\\Programs\\thanks\\target\\release\\build\\libz-sys-674c323d5947ef1f\\out\\build\\src/zlib/adler32.o" "-c" "src/zlib/adler32.c"
  cargo:warning=cc1.exe: sorry, unimplemented: 64-bit mode not compiled in
  exit code: 1

  --- stderr

  error occurred: Command "gcc.exe" "-O3" "-ffunction-sections" "-fdata-sections" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "src/zlib" "-o" "G:\\Programs\\thanks\\target\\release\\build\\libz-sys-674c323d5947ef1f\\out\\build\\src/zlib/adler32.o" "-c" "src/zlib/adler32.c" with args "gcc.exe" did not execute successfully (status code exit code: 1).
//
Wish for helps ,thanks~

**Comment by skade** [comment]
You are, for some reason, using the 32bit gcc with the 64bit toolchain. This is not an issue with the thanks app.

**Comment by tomaswuhua123** [comment]
I see， so I try to rebuild it with MinGW for 64 bit, but this time pop up another error connected to the gcc complier. After all, I believe the project it self is ok, thanks a lot.

**Comment by skade** [comment]
Thanks for following up and closing :). If you believe you hit an undocumented common case, please let us know if we can improve setup instructions.
