### ISSUE TITLE
Question to logic of contributor

### ISSUE THREAD

**Issue by sinansonmez** [rust-lang/thanks#60]
I saw my name on the contributor list of v1.76.0. It is an honour to be in the list, afaik, I didnt do any contribution to Rust directly.

https://thanks.rust-lang.org/rust/1.76.0/

**Comment by dtolnay** [comment]
It is crediting these commits, which are in https://github.com/rust-lang/rust/commit/3c999d8bf41564909c38775bb869fcd4a0da7954.

- https://github.com/rust-lang/rust-by-example/commit/e06aec8166b6ac7cdafbad19a38f6c8a33cb56f3
- https://github.com/rust-lang/rust-by-example/commit/b76736451611bc1c14d9846c5ef86a3cf5db5a60
- https://github.com/rust-lang/rust-by-example/commit/79f72941575ff20c3ef642f8eb8996558bbc6dc4

**Comment by sinansonmez** [comment]
Thanks for the explanation
